### PR TITLE
Update to GLADE and GNOME runtime 3.38

### PR DESCRIPTION
**Pull request by Eonfge**
@bilelmoussaoui Another one!

### CODE REVIEW

**Comment by Eonfge** [comment]
bot, build

**Comment by bilelmoussaoui** [comment]
Does it work ? iirc glade broke libhandy at the latest minutes as far as I can tell

**Comment by bilelmoussaoui** [comment]
My bad, missed the patch.

**Comment by Eonfge** [comment]
> My bad, missed the patch.

Would I ever push something that's janky? :rofl: 

I'm getting more and more accustomed to the whole process of package management and it's quite a bit of fun, so I'll reserve myself a few hobby-hours a week to help you and other here on Flathub.

**Pull request closed without merging**
